services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: station-simulator-db
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-station_simulator}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-station_simulator}
      POSTGRES_USER: ${POSTGRES_USER:-station_simulator}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  redis:
    image: redis:latest
    container_name: station-simulator-redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data:rw
      - redis_config:/usr/local/etc/redis/redis.conf

volumes:
  database_data:
  redis_data:
  redis_config: